# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Autobump version
        run: |
          # Parse the version number from the tag.
          VERSION=$(echo $GITHUB_REF | sed 's#.*/v##')
          VERSION_FILE='ledes_parser/__init__.py'

          # Parse the current version from the version file.
          CURRENT_VERSION=$(grep -oP '(?<=__version__ = ")[^"]*' "$VERSION_FILE")

          # Make sure the version in the tag and the version file match up.
          if [ "$CURRENT_VERSION" == "$VERSION" ]; then
              echo "Version in $VERSION_FILE is already $VERSION. No update needed."
              exit 0
          fi

          # Define the pattern to match the version string
          VERSION_PATTERN='__version__ = "\d+\.\d+\.\d+"'

          # Ensure the version pattern exists in the file
          if ! grep -q "$VERSION_PATTERN" "$VERSION_FILE"; then
              echo "Version pattern not found in $VERSION_FILE"
              exit 1
          fi

          # Replace the existing version string with the new version
          sed -i "s/$VERSION_PATTERN/__version__ = \"${VERSION}\"/g" "$VERSION_FILE"
        shell: bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish package
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*
