name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Increment package version
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        version=$(cat VERSION)
        new_version=$(echo "$version + 0.01" | bc)
        echo $new_version > VERSION
        git add VERSION
        git commit -m "Increment package version"
        git push

    - name: Publish package
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*
